#
#   --------- Api Key (Private file! Keep it safe!) ---------
#   Don't push this file to any repo! The key is protected by API (Map Embed API only)
#   and Application restrictions with HTTP referrers.
#

[build.environment]
NODE_ENV = "production"
# Pixabay API key for image search
API_KEY_PIXABAY = "***REMOVED***"
# Google Maps Api Key (Private)
API_KEY_GOOGLE = "***REMOVED***"